services:
  rimetool:
    container_name: rimetool-web
    image: python:3.11-slim
    restart: unless-stopped
    working_dir: /app
    ports:
      - "2591:2591"        # 从 2591:5001 改为 2591:2591
    environment:
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
    volumes:
      - rimetool-venv:/opt/venv
      - ./rimetool/logs:/app/rimetool/logs
    command:
      - /bin/sh
      - -lc
      - |
        set -e
        mkdir -p /app/rimetool/logs
        if [ ! -x /opt/venv/bin/python ]; then
          python -m venv /opt/venv
          . /opt/venv/bin/activate
          pip install --upgrade pip setuptools wheel
        else
          . /opt/venv/bin/activate
        fi
        pip install --upgrade rimetool
        exec /opt/venv/bin/rimetool web --port 2591 --log-dir /app/rimetool/logs

volumes:
  rimetool-venv: