# filepath: /Users/ww/coding/rimetool_new/docker-compose.yml
version: "3"
services:
  rimetool:
    container_name: rimetool  # 设置docker容器名称为rimetool
    image: whitewatercn/rimetool:latest
    ports:
      - "5023:5023"  # 映射容器的5003端口到主机的5023端口

    # ...其它配置，如环境变量、卷挂载等...